Repository waseefakhtar/dose-android, pull requests merged in 2023-11, with the labels that each got.

#95 Refactor hardcoded strings to strings.xml for better localization support
  app/src/main/java/com/waseefakhtar/doseapp/App.kt
  app/src/main/java/com/waseefakhtar/doseapp/DoseApp.kt
  app/src/main/java/com/waseefakhtar/doseapp/MedicationNotificationReceiver.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/MedicationCard.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/MedicationConfirmRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationdetail/MedicationDetailRoute.kt
  app/src/main/res/values/strings.xml
Labels: refactor

#96 Replace DatePicker with Material3 DatePickerDialog
  app/src/main/java/com/waseefakhtar/doseapp/extension/DateExtension.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/DatePickerDialogComponent.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/EndDatePickerDialog.kt
  app/src/main/java/com/waseefakhtar/doseapp/util/TimeUtils.kt
  app/src/main/res/values/strings.xml
Labels: ui

#97 Snack Bar implemented throughout the app
  app/src/main/java/com/waseefakhtar/doseapp/DoseApp.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/MedicationConfirmRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationdetail/MedicationDetailRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/util/SnackbarUtil.kt
Labels: ui

#98 Feature: Time Picker
  app/build.gradle
  app/schemas/com.waseefakhtar.doseapp.data.MedicationDatabase/1.json
  app/schemas/com.waseefakhtar.doseapp.data.MedicationDatabase/2.json
  app/src/main/java/com/waseefakhtar/doseapp/MedicationNotificationService.kt
  app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsEvents.kt
  app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsHelper.kt
  app/src/main/java/com/waseefakhtar/doseapp/data/Converters.kt
  app/src/main/java/com/waseefakhtar/doseapp/data/MedicationDatabase.kt
  app/src/main/java/com/waseefakhtar/doseapp/data/entity/MedicationEntity.kt
  app/src/main/java/com/waseefakhtar/doseapp/data/mapper/MedicationMapper.kt
  app/src/main/java/com/waseefakhtar/doseapp/domain/model/Medication.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/TimePickerDialogComponent.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/model/CalendarInformation.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/viewmodel/AddMedicationViewModel.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/history/HistoryScreen.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/MedicationCard.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/MedicationConfirmRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationdetail/MedicationDetailRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/util/TimeUtils.kt
  app/src/main/java/com/waseefakhtar/doseapp/util/TimesOfDay.kt
  app/src/main/res/values/strings.xml
Labels: feature

#102 Feature: Add support to delete additional time in AddMedication
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
Labels: ux

#105 Bump dependencies
  app/build.gradle
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationdetail/MedicationDetailRoute.kt
  build.gradle
Labels: dependency update

#107 Migrated Room to KSP
  app/build.gradle
  build.gradle
Labels: dependency update

#113 Feature: Calendar header in Home
  app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsEvents.kt
  app/src/main/java/com/waseefakhtar/doseapp/extension/DateExtension.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/data/CalendarDataSource.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/model/CalendarModel.kt
  app/src/main/res/values/strings.xml
Labels: feature
