Repository waseefakhtar/dose-android, pull requests merged in 2023-10, with the labels that each got.

#61 UX: Show Empty Card if there are no today or future medication in the list
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
Labels: ux

#62 UI: Improve vertical padding and screen title
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
Labels: ui

#73 Tracking & UI/UX: Add an event to track when app is opened from a reminder notification, improve padding, texts
  app/src/main/java/com/waseefakhtar/doseapp/DoseApp.kt
  app/src/main/java/com/waseefakhtar/doseapp/MainActivity.kt
  app/src/main/java/com/waseefakhtar/doseapp/MedicationNotificationReceiver.kt
  app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsEvents.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/MedicationConfirmRoute.kt
Labels: tracking

#78 Fix recurrence dropdown menu
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
Labels: bug

#72 adding-navigate-single-top-to-navHostController
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/navigation/AddMedicationDestination.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/navigation/HomeDestination.kt
  app/src/main/java/com/waseefakhtar/doseapp/navigation/DoseNavHost.kt
  app/src/main/java/com/waseefakhtar/doseapp/util/Utils.kt
Labels: bug

#80 Bump AGP, Gradle, and other Jetpack libraries
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: dependency update

#83 Solution for issue #79
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
Labels: ux

#82 Bugfix/add medication screen UI fix
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
Labels: ui

#90 Feature: Medication Detail Screen
  app/src/main/java/com/waseefakhtar/doseapp/DoseApp.kt
  app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsEvents.kt
  app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsHelper.kt
  app/src/main/java/com/waseefakhtar/doseapp/data/repository/MedicationRepositoryImpl.kt
  app/src/main/java/com/waseefakhtar/doseapp/extension/DateExtension.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/MedicationCard.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/navigation/HomeDestination.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/MedicationConfirmRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationdetail/MedicationDetailDestination.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationdetail/MedicationDetailRoute.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/medicationdetail/viewmodel/MedicationDetailViewModel.kt
  app/src/main/java/com/waseefakhtar/doseapp/navigation/DoseNavHost.kt
  app/src/main/java/com/waseefakhtar/doseapp/util/TimeUtils.kt
  app/src/main/res/values/strings.xml
Labels: feature

#92 Feature: History tab
  app/src/main/java/com/waseefakhtar/doseapp/DoseApp.kt
  app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsEvents.kt
  app/src/main/java/com/waseefakhtar/doseapp/extension/DateExtension.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/history/HistoryNavigation.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/history/HistoryScreen.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/history/viewmodel/HistoryState.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/history/viewmodel/HistoryViewModel.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/MedicationCard.kt
  app/src/main/java/com/waseefakhtar/doseapp/navigation/DoseNavHost.kt
  app/src/main/java/com/waseefakhtar/doseapp/navigation/DoseTopLevelNavigation.kt
  app/src/main/res/values/strings.xml
Labels: feature
