Repository waseefakhtar/dose-android, pull requests merged in 2023-12, with the labels that each got.

#122 Add lang it
  app/src/main/res/values-b+it/strings.xml
Labels: localization

#131 Add Spanish translation
  app/src/main/res/values-es/strings.xml
Labels: localization

#135 Fix issue #116 and enable predictive back gesture
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsEvents.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/navigation/AddMedicationDestination.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
  app/src/main/java/com/waseefakhtar/doseapp/feature/home/navigation/HomeDestination.kt
  app/src/main/res/values/strings.xml
Labels: crash

#134 Create strings.xml for Farsi/Persian
  app/src/main/res/values-fa/strings.xml
Labels: localization

#132 Migrate all Gradle files from Groovy to Kotlin
  app/build.gradle.kts
  build.gradle
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle
  settings.gradle.kts
Labels: refactor

#141 Fix, closes #140
  app/src/main/res/values/strings.xml
Labels: crash
